# Generated by Django 5.0.6 on 2024-06-14 20:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Processing', 'В обработке'), ('Awaiting payment', 'Ожидает оплаты'), ('Awaiting measurement', 'Ожидание технического замера'), ('Correction measurement', 'Корректировка после технического замера'), ('Preparation a sketch', 'Подготовка эскиза'), ('Processing construction', 'Обработка конструктором'), ('Production', 'Производство'), ('Preparation for delivering', 'Подготовка к доставке'), ('Delivered', 'Доставляется'), ('Montage', 'Монтаж'), ('Returned', 'Возврат'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен')], default='Processing', max_length=50, verbose_name='Статус заказа'),
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Processing', 'В обработке'), ('Awaiting payment', 'Ожидает оплаты'), ('Awaiting measurement', 'Ожидание технического замера'), ('Correction measurement', 'Корректировка после технического замера'), ('Preparation a sketch', 'Подготовка эскиза'), ('Processing construction', 'Обработка конструктором'), ('Production', 'Производство'), ('Preparation for delivering', 'Подготовка к доставке'), ('Delivered', 'Доставляется'), ('Montage', 'Монтаж'), ('Returned', 'Возврат'), ('Completed', 'Завершен'), ('Cancelled', 'Отменен')], default='Processing', max_length=50, verbose_name='Статус заказа')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'История статусов заказа',
                'verbose_name_plural': 'Истории статусов заказов',
            },
        ),
    ]
