# Generated by Django 5.0.6 on 2024-06-22 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата встречи')),
                ('time', models.TimeField(verbose_name='Время встречи')),
                ('is_booked', models.BooleanField(default=True, verbose_name='Забронирована ли встреча')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания встречи')),
            ],
            options={
                'verbose_name': 'Встреча',
                'verbose_name_plural': 'Встречи',
            },
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(choices=[('not_commited', 'Не совершена'), ('commited', 'Совершена')], default='not_commited', max_length=255, unique=True, verbose_name='Название статуса встречи')),
            ],
            options={
                'verbose_name': 'Статус',
                'verbose_name_plural': 'Статусы',
            },
        ),
    ]
