# Generated by Django 5.0.6 on 2024-06-23 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('classic', 'Классика'), ('minimalism', 'Минимализм'), ('modern', 'Модерн'), ('scandinavian', 'Скандинавский'), ('simple', 'Простой')], default='classic', max_length=255, unique=True, verbose_name='Стиль'),
        ),
    ]
