# Generated by Django 5.0.6 on 2024-06-23 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='material_apron',
            field=models.CharField(choices=[('dsp', 'ДСП')], default='dsp', max_length=255, verbose_name='Материал фартука'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_facade',
            field=models.CharField(choices=[('mdf_cpf_plastic', 'МДФ + CPL пластик'), ('mdf_pvx_tape', 'МДФ + ПВХ пленка'), ('mdf_enamel', 'МДФ + Эмаль')], default='mdf_cpf_plastic', max_length=255, verbose_name='Материал фасада'),
        ),
        migrations.AlterField(
            model_name='product',
            name='material_table_top',
            field=models.CharField(choices=[('hpl_compact', 'HPL - компакт'), ('dsp', 'ДСП')], default='hpl_compact', max_length=255, verbose_name='Материал столешницы'),
        ),
        migrations.AlterField(
            model_name='product',
            name='style',
            field=models.CharField(choices=[('classic', 'Классика'), ('minimalism', 'Минимализм'), ('modern', 'Модерн'), ('scandinavian', 'Скандинавский'), ('simple', 'Простой')], default='classic', max_length=255, verbose_name='Стиль'),
        ),
    ]
